export const UPDATE_BIRDS_STATUS = 'BIRDS_DATA/CHANGE_BIRDS_STATUS';
export const CHANGE_BIRDS_DATA = 'BIRDS_DATA/CHANGE_BIRDS_DATA';
export const CHANGE_ANSWER_STATUS = 'APP/CHANGE_ANSWER_STATUS';
export const NEXT_QUESTION = 'APP/NEXT_QUESTION';
export const CHANGE_POINTS = 'APP/CHANGE_POINTS';
export const CHANGE_SCORE = 'APP/CHANGE_SCORE'